services:
  app:
    build: ./app
    ports:
      - 5000:5000
    networks:
      - sandbox-net

  prometheus:
    image: prom/prometheus:v3.4.2
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - 9090:9090
    networks:
      - sandbox-net

  node-exporter:
    image: prom/node-exporter:v1.9.1
    ports:
      - 9100:9100
    networks:
      - sandbox-net

  alertmanager:
    image: prom/alertmanager:v0.28.1
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - sandbox-net

  grafana:
    image: grafana/grafana:12.0.2-ubuntu
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - sandbox-net

volumes:
  grafana-data:

networks:
  sandbox-net:
