[project]
name = "mon-serv-flask"
version = "0.1.0"
description = "simple Flask web app that can trigger high CPU usage"
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "prometheus-client>=0.22.1",
]
